import { mongoCollections } from "@/lib/mongodb/collections";

export async function ensureMongoIndexes(): Promise<void> {
  const [
    users,
    profiles,
    topics,
    memberships,
    messages,
    upvotes,
    polls,
    pollVotes,
    dutyOffers,
    rides,
    rideOffers,
    liveLocations,
    pushSubscriptions,
    payments,
  ] = await Promise.all([
    mongoCollections.users(),
    mongoCollections.profiles(),
    mongoCollections.topics(),
    mongoCollections.topicMemberships(),
    mongoCollections.messages(),
    mongoCollections.messageUpvotes(),
    mongoCollections.polls(),
    mongoCollections.pollVotes(),
    mongoCollections.dutyOffers(),
    mongoCollections.rides(),
    mongoCollections.rideOffers(),
    mongoCollections.rideLiveLocations(),
    mongoCollections.pushSubscriptions(),
    mongoCollections.payments(),
  ]);

  await Promise.all([
    users.createIndex({ email: 1 }, { unique: true }),
    users.createIndex({ verificationTokenHash: 1 }, { sparse: true }),
    profiles.createIndex({ userId: 1 }, { unique: true }),
    profiles.createIndex({ chakra: -1 }),
    topics.createIndex({ location: "2dsphere" }),
    topics.createIndex({ createdAt: -1 }),
    topics.createIndex({ lastActivityAt: -1 }),
    topics.createIndex({ createdByUserId: 1, createdAt: -1 }),
    memberships.createIndex({ topicId: 1, userId: 1 }, { unique: true }),
    memberships.createIndex({ userId: 1, joinedAt: -1 }),
    messages.createIndex({ "scope.kind": 1, "scope.id": 1, createdAt: 1 }),
    messages.createIndex({ topicId: 1, createdAt: 1 }),
    messages.createIndex({ senderUserId: 1, createdAt: -1 }),
    upvotes.createIndex({ messageId: 1, userId: 1 }, { unique: true }),
    polls.createIndex({ topicId: 1, createdAt: 1 }),
    pollVotes.createIndex({ pollId: 1, userId: 1 }, { unique: true }),
    dutyOffers.createIndex({ dutyId: 1, createdAt: 1 }),
    dutyOffers.createIndex({ dutyId: 1, helperUserId: 1 }, { unique: true }),
    rides.createIndex({ status: 1, createdAt: -1 }),
    rides.createIndex({ riderUserId: 1, createdAt: -1 }),
    rides.createIndex({ pickupLocation: "2dsphere" }),
    rides.createIndex({ dropLocation: "2dsphere" }),
    rideOffers.createIndex({ rideId: 1, createdAt: 1 }),
    rideOffers.createIndex({ rideId: 1, driverUserId: 1 }, { unique: true }),
    liveLocations.createIndex({ rideId: 1, userId: 1 }, { unique: true }),
    liveLocations.createIndex({ updatedAt: 1 }, { expireAfterSeconds: 60 * 60 * 6 }),
    pushSubscriptions.createIndex({ endpoint: 1 }, { unique: true }),
    pushSubscriptions.createIndex({ userId: 1, endpoint: 1 }, { unique: true }),
    payments.createIndex({ "context.kind": 1, "context.id": 1 }),
    payments.createIndex({ payerUserId: 1, createdAt: -1 }),
    payments.createIndex({ payeeUserId: 1, createdAt: -1 }),
  ]);
}
